app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::group(['middleware' => 'admin'], function () {


    /**************** Dynamic Contents **************************/
    Route::resource('dynamic-contents', 'DynamicContentController');

    /**************** Album **************************/
    Route::resource('albums', 'AlbumController');


    /**************** Photos ************************/
    Route::resource('photos', 'PhotoController', ['except' => 'show']);
    Route::get('photo-album/{albumID}/{page?}', 'PhotoController@getPhotosByAlbum');


    /*************** Profiles *******************/
   
    /*************** ArtCategories ***************/
    Route::resource('categories', 'CategoryController');
    
    Route::get('getParentCategories', 'CategoryController@getParentCategories');


    /*************** Sliders ***************/
    Route::resource('sliders', 'SliderController');


    /*************** Article ************************/
    Route::resource('articles', 'ArticleController', ['except' => 'show']);
    Route::get('articlesExport', 'ArticleController@export');
    
    Route::get('articlesImportFileSelect', 'ArticleController@import');
    Route::post('articlesImportData', ['as' =>'importData','uses' => 'ArticleController@importData']);

    /*************** Users ************************/
    Route::resource('users', 'UserController');
    Route::get('userstatus/{id}/{status}', 'UserController@changeStatus');
    
    Route::post('updateProfile', ['as'=>'updateProfile','uses' =>'UserController@updateProfile'] );
    
    /***************Information Officers****************************/
    Route::resource('infoOfficers','InfoOfficerController');
    Route::get('infoOfficerImportFileSelect', 'InfoOfficerController@import');
    Route::post('importData', ['as' =>'importInfoOfficerData','uses' => 'InfoOfficerController@importData']);
        
    /*************Office*************************************/
    Route::resource('offices','OfficeController');
Route::post('image/upload','ImageController@uploadMultipleImage');

Route::get('photo_delete/{id}',['as'=>'photo_delete','uses'=>'PhotoController@destroy']);
Route::get('articles_delete/{ids}', 'ArticleController@destroy');

Route::post(
    'article/search','ArticleController@articleSearch');

Route::post(
    'categoryBy/search',
    array(
        'as' => 'category.search',
        'uses' => 'CategoryController@categorySearch'
    )
);

Route::post(
    'slider/search',
    array(
        'as' => 'slider.search',
        'uses' => 'SliderController@sliderSearch'
    )
);

Route::post(
    'dynamic/search',
    array(
        'as' => 'dynamic.search',
        'uses' => 'DynamicContentController@dynamicSearch'
    )
);

Route::post(
    'office/search',
    array(
        'as' => 'office.search',
        'uses' => 'OfficeController@OfficeSearch'
    )
);
Route::post(
    'infoOffice/search',
    array(
        'as' => 'infooffice.search',
        'uses' => 'InfoOfficerController@infoOfficeSearch'
    )
);

Route::post(
    'album/search',
    array(
        'as' => 'album.search',
        'uses' => 'AlbumController@albumSearch'
    )
);


Route::resource('important_links','ImportantLinkController');

});


/* for Multilanguage support and switching */
Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect']
], function () {

    /***************    Front End   *********************************************/
    Route::get('/', 'FrontEndController@index');
    Route::get('/home', 'FrontEndController@index');
    Route::get('/dashboard', 'DashboardController@index');
    Route::get('articles/{id}/{category}', 'ArticleController@getArticlesByCategory');
    Route::get('articleDescription/{id}', 'ArticleController@getSingleArticleById');
    Route::get('displayPdfContent/{documents}', 'ArticleController@displayPdfContent');

    /*************** Dynamic Content ************************/
    Route::resource('dynamic-contents', 'DynamicContentController', ['only' => 'show']);
    Route::resource('articles', 'ArticleController', ['only' => 'show']);
    Route::resource('photos', 'PhotoController', ['only' => 'show']);

Route::get('importantLinks/getAll', 'ImportantLinkController@getAllImportantLinks');
Route::get('contactUs','FrontEndController@contact');

Route::get('showBiodata/{id}','DynamicContentController@showBiodata');

Route::get('whatWeDo','FrontEndController@getDetailsForWhatWeDo');
Route::get('procedureToRequest','FrontEndController@getDetailsProcedureToRequest');
Route::get('rightsToKnow','FrontEndController@getDetailsRightsToKnow');


Route::get('aboutus', 'DynamicContentController@displayContentOfAboutUs');
Route::get('staffDetails', 'DynamicContentController@displayStaffDetails');
Route::get('getAllSliderContents', 'SliderController@getAllSliderContents');


/******************Search MOdule**********************************************/
   
    Route::get('searchInfoOfficersByOthers', 'InfoOfficerController@searchInfoOfficersByOthers');
    Route::get('searchInfoOfficersByDistrict', 'InfoOfficerController@searchInfoOfficersByDistrict');
    Route::get('getInfoOfficerDetailsByDistrict/{value}', 'InfoOfficerController@getInfoOfficerDetailsByDistrict');
    Route::get('getInfoOfficerDetailsByCentral/', 'InfoOfficerController@getInfoOfficerDetailsByCentral');
    Route::get('getInfoOfficerDetailsByOthers/{value}', 'InfoOfficerController@getInfoOfficerDetailsByOthers');

   
Route::post('search', ['as' =>'posts.search','uses' => 'ArticleController@postSearch']);
});

resources/views/admin/dynamics/create.blade.php
@extends('admin')
@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Add Content</h3>
    </div>
@stop
@section('adminContent')
    <div class = "article-content">
        {!! Form::open(['route'=>'dynamic-contents.store','files' => true])!!}

            <fieldset>
                 <div class="form-group">
                                     <label><b>TITLE (English)</b></label>
                                     {!! Form::text('title_en',null,array('class'=>'form-control','placeholder'=>'English')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>TITLE (Nepali)</b></label>
                                     {!! Form::text('title_ne',null,array('class'=>'form-control','placeholder'=>'Nepali')) !!}
                                 </div>
                 <div class="panel-body">
                                     <div class="tab-content">
                                         <ul class="nav nav-tabs">
                                            <li class="active"><a href="#tab1primary" data-toggle="tab">English</a></li>
                                            <li><a href="#tab2primary" data-toggle="tab"> Nepali</a></li>
                                            
                                         </ul>
                                          <div class="tab-pane fade in active" id="tab1primary">
                                            <ul>
                                            {!! Form::textarea('description_en',null,array('class'=>'form-control text-editor','placeholder'=>'English')) !!}
                               
                                            </ul>
                                        </div>
                                        <div class="tab-pane fade" id="tab2primary">
                                            <ul>
                                            {!! Form::textarea('description_ne',null,array('class'=>'form-control text-editor','placeholder'=>'Nepali')) !!}
                              
                                            </ul>

                                        </div>
                                      </div>
                                  </div>
                 <div class="form-group">
                <label><b>STATUS</b></label>
                {!! Form::select('status', ['Draft'=>'Draft','Published'=>'Published']) !!}
            </div>
                 <div class="form-group">
                    <label><b>IMAGE</b></label>
                    {!! Form::file('image_file',null,array('class'=>'form-control','id'=>'file_uploader')) !!}
                    {!! Form::text('image',null,array('class'=>'form-control','id'=> 'file-name','disabled'=>"disabled")) !!}
                </div>
                   <div class="form-group">
                       <label><b>NAME</b></label>
                      {!! Form::select('user_id', $portfolioLists) !!}
                  </div>

                <center>{!! form::submit('Add',[' class'=>'btn btn-primary form-control'])!!}</center>

            </fieldset>
        {!! Form::close()!!}
        @if($errors->any())
            <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                   <li> {{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </div>

@stop

resources/views/admin/dynamics/edit.blade.php
@extends('admin')
@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Edit Content</h3>
    </div>
@stop
@section('adminContent')
    <div class = "article-content">
       {!! Form::model($dynamics,array('method' => 'PATCH','route'=>array('dynamic-contents.update',$dynamics->id))) !!}


            <fieldset>
                  <div class="form-group">
                                     <label><b>TITLE (English)</b></label>
                                     {!! Form::text('title_en',null,array('class'=>'form-control','placeholder'=>'English')) !!}
                                 </div>
                                 <div class="form-group">
                                     <label><b>TITLE (Nepali)</b></label>
                                     {!! Form::text('title_ne',null,array('class'=>'form-control','placeholder'=>'Nepali')) !!}
                                 </div>
                 <div class="panel-body">
                                     <div class="tab-content">
                                         <ul class="nav nav-tabs">
                                            <li class="active"><a href="#tab1primary" data-toggle="tab">English</a></li>
                                            <li><a href="#tab2primary" data-toggle="tab"> Nepali</a></li>
                                            
                                         </ul>
                                          <div class="tab-pane fade in active" id="tab1primary">
                                            <ul>
                                            {!! Form::textarea('description_en',null,array('class'=>'form-control text-editor','placeholder'=>'English')) !!}
                               
                                            </ul>
                                        </div>
                                        <div class="tab-pane fade" id="tab2primary">
                                            <ul>
                                            {!! Form::textarea('description_ne',null,array('class'=>'form-control text-editor','placeholder'=>'Nepali')) !!}
                              
                                            </ul>

                                        </div>
                                      </div>
                                  </div>
                 <div class="form-group">
                     <label><b>STATUS</b></label>
                     {!! Form::text('status',null,array('class'=>'form-control')) !!}
                 </div>
                 <div class="form-group">
                    <label><b>IMAGE</b></label>
                    {!! Form::file('image_upload',null,array('class'=>'form-control','id'=>'file_uploader')) !!}
                    {!! Form::text('image',null,array('class'=>'form-control','id'=> 'file-name','disabled'=>"disabled")) !!}
                </div>
                   <div class="form-group">
                       <label><b>NAME</b></label>
                      {!! Form::select('user_id', $portfolioLists) !!}
                  </div>

                <center>{!! form::submit('Update',[' class'=>'btn btn-primary form-control'])!!}</center>

            </fieldset>
        {!! Form::close()!!}
        @if($errors->any())
            <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                   <li> {{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </div>

@stop

resources/views/admin/dynamics/index.blade.php
@extends('admin')

@section('breadcrumb')
 
    <h3 class="panel-title">Content</h3>
    <div class="sub-menu">
        <a href="{{url('dynamic-contents/create')}}"><i class="fa fa-plus-circle fa-2x pull-right"></i></a>
    </div>
@stop

@section('adminContent')
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <th> ID</th>
            <th> TITLE</th>
            <th> TYPE</th>
            <th> STATUS</th>
            <th> USERNAME</th>
            <th> ACTIONS</th>
            </thead>
            <tbody>
               @foreach($dynamics as $dynamic)
                <tr>
                 <td>{!! $dynamic->id !!}</td>
                 <td>{!! $dynamic->title_en !!}</td>
                  <td>{!! $dynamic->type !!}</td>
                 <td>{!! $dynamic->status !!}</td>
                 <td>{!! $dynamic->user->all()[0]->username !!}</td>
                 <td>{!! link_to_route('dynamic-contents.edit', '', array($dynamic->id),array('class' => 'fa fa-pencil fa-fw')) !!}</td>

                <td><button type="button" id="delete-button" class="delete-button" data-url = "{!! url('dynamic-contents')."/".$dynamic->id !!}"><i class="fa fa-trash-o"></i></button>
                </td>
               @endforeach
              </tr>
            </tbody>
        </table>

    </div>
@stop