app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::group(['middleware' => 'admin'], function () {


    /**************** Dynamic Contents **************************/
    Route::resource('dynamic-contents', 'DynamicContentController');

    /**************** Album **************************/
    Route::resource('albums', 'AlbumController');


    /**************** Photos ************************/
    Route::resource('photos', 'PhotoController', ['except' => 'show']);
    Route::get('photo-album/{albumID}/{page?}', 'PhotoController@getPhotosByAlbum');


    /*************** Profiles *******************/
   
    /*************** ArtCategories ***************/
    Route::resource('categories', 'CategoryController');
    
    Route::get('getParentCategories', 'CategoryController@getParentCategories');


    /*************** Sliders ***************/
    Route::resource('sliders', 'SliderController');


    /*************** Article ************************/
    Route::resource('articles', 'ArticleController', ['except' => 'show']);
    Route::get('articlesExport', 'ArticleController@export');
    
    Route::get('articlesImportFileSelect', 'ArticleController@import');
    Route::post('articlesImportData', ['as' =>'importData','uses' => 'ArticleController@importData']);

    /*************** Users ************************/
    Route::resource('users', 'UserController');
    Route::get('userstatus/{id}/{status}', 'UserController@changeStatus');
    
    Route::post('updateProfile', ['as'=>'updateProfile','uses' =>'UserController@updateProfile'] );
    
    /***************Information Officers****************************/
    Route::resource('infoOfficers','InfoOfficerController');
    Route::get('infoOfficerImportFileSelect', 'InfoOfficerController@import');
    Route::post('importData', ['as' =>'importInfoOfficerData','uses' => 'InfoOfficerController@importData']);
        
    /*************Office*************************************/
    Route::resource('offices','OfficeController');
Route::post('image/upload','ImageController@uploadMultipleImage');

Route::get('photo_delete/{id}',['as'=>'photo_delete','uses'=>'PhotoController@destroy']);
Route::get('articles_delete/{ids}', 'ArticleController@destroy');

Route::post(
    'article/search','ArticleController@articleSearch');

Route::post(
    'categoryBy/search',
    array(
        'as' => 'category.search',
        'uses' => 'CategoryController@categorySearch'
    )
);

Route::post(
    'slider/search',
    array(
        'as' => 'slider.search',
        'uses' => 'SliderController@sliderSearch'
    )
);

Route::post(
    'dynamic/search',
    array(
        'as' => 'dynamic.search',
        'uses' => 'DynamicContentController@dynamicSearch'
    )
);

Route::post(
    'office/search',
    array(
        'as' => 'office.search',
        'uses' => 'OfficeController@OfficeSearch'
    )
);
Route::post(
    'infoOffice/search',
    array(
        'as' => 'infooffice.search',
        'uses' => 'InfoOfficerController@infoOfficeSearch'
    )
);

Route::post(
    'album/search',
    array(
        'as' => 'album.search',
        'uses' => 'AlbumController@albumSearch'
    )
);


Route::resource('important_links','ImportantLinkController');

});


/* for Multilanguage support and switching */
Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect']
], function () {

    /***************    Front End   *********************************************/
    Route::get('/', 'FrontEndController@index');
    Route::get('/home', 'FrontEndController@index');
    Route::get('/dashboard', 'DashboardController@index');
    Route::get('articles/{id}/{category}', 'ArticleController@getArticlesByCategory');
    Route::get('articleDescription/{id}', 'ArticleController@getSingleArticleById');
    Route::get('displayPdfContent/{documents}', 'ArticleController@displayPdfContent');

    /*************** Dynamic Content ************************/
    Route::resource('dynamic-contents', 'DynamicContentController', ['only' => 'show']);
    Route::resource('articles', 'ArticleController', ['only' => 'show']);
    Route::resource('photos', 'PhotoController', ['only' => 'show']);

Route::get('importantLinks/getAll', 'ImportantLinkController@getAllImportantLinks');
Route::get('contactUs','FrontEndController@contact');

Route::get('showBiodata/{id}','DynamicContentController@showBiodata');

Route::get('whatWeDo','FrontEndController@getDetailsForWhatWeDo');
Route::get('procedureToRequest','FrontEndController@getDetailsProcedureToRequest');
Route::get('rightsToKnow','FrontEndController@getDetailsRightsToKnow');


Route::get('aboutus', 'DynamicContentController@displayContentOfAboutUs');
Route::get('staffDetails', 'DynamicContentController@displayStaffDetails');
Route::get('getAllSliderContents', 'SliderController@getAllSliderContents');


/******************Search MOdule**********************************************/
   
    Route::get('searchInfoOfficersByOthers', 'InfoOfficerController@searchInfoOfficersByOthers');
    Route::get('searchInfoOfficersByDistrict', 'InfoOfficerController@searchInfoOfficersByDistrict');
    Route::get('getInfoOfficerDetailsByDistrict/{value}', 'InfoOfficerController@getInfoOfficerDetailsByDistrict');
    Route::get('getInfoOfficerDetailsByCentral/', 'InfoOfficerController@getInfoOfficerDetailsByCentral');
    Route::get('getInfoOfficerDetailsByOthers/{value}', 'InfoOfficerController@getInfoOfficerDetailsByOthers');

   
Route::post('search', ['as' =>'posts.search','uses' => 'ArticleController@postSearch']);
});

app/Http/Controllers/ArtCategoryController.php
<?php namespace App\Http\Controllers;


use App\Http\Requests;
use App\Repository\ArtCategory as ArtCategory;
use App\Http\Requests\CreateArtCategoryRequest;
use Request;
use Session;

/**
 * Class ArtCategoryController
 * @package App\Http\Controllers
 */
class ArtCategoryController extends Controller
{
    /**
     * @var int
     */
    private $count;

    /*
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

        $this->count = 10;
    }

    /**
     * @param ArtCategory $artCategory
     * @return $this
     */
    public function index(ArtCategory $artCategory)
    {

        $artcategories = $artCategory->paginate($this->count);
        return view('admin.artCategories.index',compact('artcategories'));
    }


    /**
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admin.artCategories.create');
    }


    /**
     * @param CreateArtCategoryRequest $request
     * @param ArtCategory $artCategory
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CreateArtCategoryRequest $request, ArtCategory $artCategory)
    {

        $artCategory->create($request->all());
        Session::flash('message', 'The Art Category was successfully added!.');
        Session::flash('flash_type', 'alert-success');
        return redirect('artcategories');
    }

    /**
     * @param $id
     * @param ArtCategory $artCategory
     * @return $this
     */
    public function show($id, ArtCategory $artCategory)
    {
        //return view('artCategories.index')->with('artCategory', $artCategory->find($id));
    }

    /**
     * @param $id
     * @param ArtCategory $artCategory
     * @return $this
     */
    public function edit($id, ArtCategory $artCategory)
    {

        return view('admin.artCategories.edit')->with('artCategory', $artCategory->find($id));
    }


    /**
     * @param $id
     * @param ArtCategory $artCategory
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update($id, CreateArtCategoryRequest $request, ArtCategory $artCategory)
    {
        $artCategory->find($id)->update($request->all());
        Session::flash('message', 'The Art Category was successfully edited!.');
        Session::flash('flash_type', 'alert-success');
        return redirect('artcategories');
    }


    /**
     * @param $id
     */
    public function destroy($id)
    {

    }

    /**
     * @param ArtCategory $artCategory
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function getAllArtCategory(ArtCategory $artCategory)
    {
        return $artCategory->all(array('id', 'name'))->take(20);
    }

}

resources/views/admin/artCategories/create.blade.php
@extends('admin')

@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Add Category</h3>
    </div>
@stop

@section('adminContent')
    <div class = "article-content">

                        {!! Form::open(['route'=>'categories.store'])!!}

                            <fieldset>
                                 <div class="form-group">
                                     <label><b>NAME</b></label>
                                     {!! Form::text('name',null,array('class'=>'form-control')) !!}
                                 </div>
	                                <div class="form-group">
	                				 <label><b>TYPE</b></label>
	                				{!! Form::select('menuType', array('Select'=>'Select','Parent'=>'Parent','Child'=>'Child'),null,array('id' => 'menuType')) !!}
	            					</div>
                              <div class="form-group">
	                				 <label><b>Parent Menu</b></label>
                              {!! Form::select('parentMenuType', array('Select'=>'Select'),null,array('id' => 'parentMenuType')) !!}
                              </div>
                                    
                                 <div class="form-group">
                                     <label><b>DESCRIPTION</b></label>
                                     {!! Form::textarea('description',null,array('class'=>'form-control')) !!}
                                 </div>


                                <center>{!! form::submit('Add',[' class'=>'btn btn-primary form-control'])!!}</center>

                            </fieldset>
                        {!! Form::close()!!}

                    </div>
@stop

resources/views/admin/artCategories/edit.blade.php
@extends('admin')

@section('breadcrumb')
    <div class = "portfolio-content-header">
        <h3 class="panel-title">Edit Category</h3>
    </div>
@stop

@section('adminContent')
    <div class = "artCategory-content">
                        {!!Form::model($category, array('method'=>'PATCH','route'=>array('categories.update',$category->id)))!!}

                            <fieldset>
                                 <div class="form-group">
                                     <label><b>NAME</b></label>
                                     {!! Form::text('name',null,array('class'=>'form-control')) !!}
                                 </div>
                                  <div class="form-group">
	                				 <label><b>TYPE</b></label>
	                				{!! Form::select('menuType', array('Select'=>'Select','Parent'=>'Parent','Child'=>'Child'),null,array('id' => 'menuType')) !!}
	            					</div>
                              <div class="form-group">
	                				 <label><b>Parent Menu</b></label>
                              {!! Form::select('parentMenuType', array('Select'=>'Select'),null,array('id' => 'parentMenuType')) !!}
                              </div>
                                    
                                 <div class="form-group">
                                     <label><b>DESCRIPTION</b></label>
                                     {!! Form::textarea('description',null,array('class'=>'form-control')) !!}
                             </div>


                                <center>{!! form::submit('Update',[' class'=>'btn btn-primary form-control'])!!}</center>

                            </fieldset>
                        {!! Form::close()!!}

                    </div>

@stop

resources/views/admin/artCategories/index.blade.php
@extends('admin')

@section('breadcrumb')
<div class="row">
  <div class="col-md-3">
    <h3 class="panel-title">Category</h3>
  </div>
  <div class="col-md-4">

{!! Form::open(array('method' => 'Post', 'url' => 'categoryBy/search')) !!}

            <div class="form-group">
                <label class="sr-only" for="search_text">Search Text</label>
                {!! Form::text('search_text',null,array('class'=>'form-control', 'placeholder' => 'Search Category')) !!}
            </div>
</div>
<div class="col-md-2">

{!! form::submit('Search',[' class'=>'btn btn-primary form-control'])!!}
{!! Form::close() !!}
</div>

<div class="col-md-3">
    <div class="sub-menu">
        <a href="{{url('categories/create')}}"><i class="fa fa-plus-circle fa-2x pull-right"></i></a>
    </div>
</div>
</div>
@stop

@section('adminContent')
    <div class="table-responsive art-content">
        <table class="table table-hover table-striped">
            <thead>
            <th> NAME</th>
            <th> ACTIONS</th>
            </thead>
            <tbody>
            @foreach($categoriesView as $category)
                <tr>
                    <td>{!! $category->name!!}</td>
                    <td>{!! link_to_route('categories.edit', '', array($category->id),array('class' => 'fa fa-pencil fa-fw')) !!}</td>
                   <td>
{!! Form::open(['method' => 'DELETE', 'route' => ['categories.destroy', $category->id]]) !!}
    {!! Form::button('<span class="fa fa-trash-o"></span>', array('class'=>'btn btn-default', 'type'=>'submit')) !!}
                                      
{!!Form::close() !!}
</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pagination"> {!! $categoriesView->render() !!}</div>
    </div>
@stop